### ISSUE TITLE
gogs docker fails on Kubernetes

### ISSUE THREAD

**Issue by kai0** [gogits/gogs#1815]
Kubernetes (http://kubernetes.io/) gogs config files:

- gogs-rc.yaml

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: gogs
spec:
  replicas: 1
  selector:
    name: gogs
  template:
    metadata:
      labels:
        name: gogs
    spec:
      containers:
        - name: gogs
          image: gogs/gogs
          ports:
            - containerPort: 3000
            - containerPort: 22
          volumeMounts:
            - mountPath: /data
              name: data
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
          env:
            - name: POSTGRES_USER
              value: "gogs"
            - name: POSTGRES_PASSWORD
              value: "gogs"
      volumes:
        - name: data
          hostPath:
            path: /var/gogs
        - name: postgres
          hostPath:
            path: /var/gogs-postgres
```

- gogs-service.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  name: gogs
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 33000
      name: a
    - port: 22
      protocol: TCP
      nodePort: 30022
      name: b
  selector:
    name: gogs
```

Steps to reproduce:
1. kubectl create -f gogs-rc.yaml
2. kubectl create -f gogs-service.yaml
3. kubectl stop rc gogs
4. kubectl create -f gogs-rc.yaml

Expected result:
- Gogs accessible from host:33000.

Actual result:
- web.go:587 runWeb()] [E] Fail to start server: listen tcp 0.0.0.0:3000: bind: address already in use
