### ISSUE TITLE
Repository headline renders extremely thin 

### ISSUE THREAD

**Issue by max-m** [gogits/gogs#2087]
### Gogs Version
Gogs: Go Git Service 0.7.22.1125 Beta
### Browser
Firefox 43.0a2 (2015-10-29) on Ubuntu 15.04

### Problem description
![bildschirmfoto vom 2015-12-02 16 47 52](https://cloud.githubusercontent.com/assets/642457/11548328/816caa18-995b-11e5-90bb-d0df7271f41a.png)

As you can see the headline renders extremely thin. This happens because of the `font-weight: 300;` which is set on that element and the fact that I have the Lato font family (with its different weights) installed on my system. Rather than using the normal Lato font Firefox chooses “Lato Hairline” as it considers it to be more fitting for that weight.

After changing
```css
.repository .head .ui.huge.breadcrumb {
    font-size: 1.7rem;
    font-weight: 300;
}
```
to
```css
.repository .head .ui.huge.breadcrumb {
    font-size: 1.7rem;
    font-weight: 400;
}
```
it looks fine on my system:
![bildschirmfoto vom 2015-12-03 01 30 44](https://cloud.githubusercontent.com/assets/642457/11548502/7eea889e-995d-11e5-81c5-a0e85fd8c4dc.png)
