### ISSUE TITLE
UI: codes appear too cramped to line numbers

### ISSUE THREAD

**Issue by initbar** [gogits/gogs#2716]
- Gogs version (or commit ref): `2016 Gogs Version: 0.8.47.0227 (latest)`
- Git version: `git version 1.9.1`
- Operating system: `Linux 14.04.1-Ubuntu x86_64`
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite

### Description
I think codes are too close to the line numbers. [For example](https://try.gogs.io/danil/init.el/src/master/my-init.el#L36-L59):

![sample](https://cloud.githubusercontent.com/assets/12630151/13381636/a431ca16-de2e-11e5-9d36-a3b75fa7b04d.png)

I think (following GitHub's UI design) [equal padding](https://github.com/initbar/gogs/commit/bd46b88a76482a4f1ea0298ae06bd05234afd105) to the left (of `lines-code` class) as much as there are pixels to the padding to the right (of `lines-num` class).

**Comment by initbar** [comment]
Should I make a pull request (if my [commit](https://github.com/initbar/gogs/commit/bd46b88a76482a4f1ea0298ae06bd05234afd105) is acceptable)?

**Comment by Unknwon** [comment]
Thanks, but I think you patch does not fix anything or maybe I test it wrongly. Can you take a screenshot?

**Comment by Unknwon** [comment]
Thanks for the screenshot, but the final result on DOM does not seem line number has equal padding?

**Comment by initbar** [comment]
@neolit123 Thanks!

The `10px` padding on left and right looks much better based on the following addition:

```css
.lines-num {
  0 10px 0 0 !important;
}

.lines-code {
  0 0 0 10px !important;
}
```

![screenshot](https://cloud.githubusercontent.com/assets/12630151/13436668/6fc5c5da-dfae-11e5-8445-5d1f6ca069dd.png)

**Comment by neolit123** [comment]
@initbar, github also has the ```min-width: 50px;``` for the line number area (e.g. ```.lines-num```).

**Comment by initbar** [comment]
@neolit123 Of course - I think although the `min-width: 50px` doesn't affect the structure initially, but useful for reduced `vw`.

I've made minor adjustments to the colors so that the top bar and line background doesn't look flushed out from the global "white" theme.

```css
.ui.attached.header {
    background-color: #fefefe; /* (changed from) background: #f0f0f0 */
}

.repository.file.list #file-content .code-view .lines-num {
    vertical-align: top;
    text-align: right;
    color: #999;
    background-color: #fafafa; /* (changed from) background: #f5f5f5 */
    width: 1%;
    min-width: 50px; /* (added) */
}

/* (added) */
.lines-num {
    padding: 0 10px 0 0 !important;
    border: solid #eee;
    border-width: 0 1px 0 0;
}

/* (added)
  this is for the event when cursor is hovering over the line numbers.
 */
.lines-num *:hover {
    color: #0a0a0a;
}

/* (added) */
.lines-code {
  padding: 0 0 0 10px !important;
}
```

### Before:

![before](https://cloud.githubusercontent.com/assets/12630151/13438200/012f8054-dfb6-11e5-90bf-0ca633517b0c.png)

### After:

![after](https://cloud.githubusercontent.com/assets/12630151/13438205/08994eba-dfb6-11e5-9ee9-2a4537d50d3d.png)

**Comment by initbar** [comment]
And enhanced top 3 buttons:

```css
/* will be changed for more direct pointer to top 3 buttons */
.ui.button {
    background-color: #fefefe;  /* (changed from) background: #e0e1e2; */
    border: solid #e0e0e0;  /* (changed from) border: none; */
    border-width: 1px;  /* (added) */
    color: rgba(0,0,0,0.9);  /* (changed from) color: rgba(0,0,0,.6); */
}
```

### Before:
![before](https://cloud.githubusercontent.com/assets/12630151/13438715/346ca76a-dfb8-11e5-846f-61b6a81bb450.png)

### After:
![after](https://cloud.githubusercontent.com/assets/12630151/13438714/34469b88-dfb8-11e5-8504-077fdf0ccd21.png)
