### ISSUE TITLE
Gogs panic on 0.9.13.0318

### ISSUE THREAD

**Issue by thypon** [gogits/gogs#2886]
- Gogs version (or commit ref): 0.9.13.0318
- Git version: 2.6.4
- Operating system: docker image
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
https://gist.github.com/thypon/364f3cd991a1da092138

## Description

gogs panic on 0.9.13.0318, doesn't happen with 0.9.0.0306 with the same data folder.

**Comment by Unknwon** [comment]
Hi, I think you did not follow what you're asked to do, which is delete old templates directory and copy the new one.

**Comment by thypon** [comment]
```
  gogs:
    image: gogs/gogs
    run:
      volume: ["data/gogs:/data"]
      detach: true
```
this was the command line through crane. I volumed only the data directory.
