### ISSUE TITLE
SOCAT_LINK does not work with docker embedded DNS

### ISSUE THREAD

**Issue by ollin** [gogits/gogs#3292]
- Docker Image: gogs/gogs:0.9.46
- Docker: 1.11.2
- Gogs version 0.9.46.0717
- git version 2.6.6

Hello,

I'm using gogs in a docker-compose.yml file. I link postgres:

```
...
  gogs:
    image: gogs/gogs:0.9.46
    container_name: gogs
    ports:
      - "10080:3000"
    environment:
      - SOCAT_LINK=true
    volumes:
      - gogs-data:/data
    links:
      - db
...
```

but socat is not used. I think the problem is, that since docker 1.10 docker is using an embedded DNS server and the links are not available as environment variables anymore.

If I go into the gogs container via exec, I can not found any environment variable which is needed by the logic inside the  [start.sh](https://github.com/gogits/gogs/blob/master/docker/start.sh#L21) script. ``$(env | sed -En ...``

1.) I think this needs a fix.
2.) Is there a workaround so that I can connect to postgres and not have the situation as described in #2015 

Edit: 
I'm using docker compose v2 format.

**Comment by ollin** [comment]
Found a workaround:

``dns_search: .`` removes the search entry from /etc/resolv.conf, which was used in my case

After using that option it was possible to configure postgres via

``HOST     = db:5432``

The final section inside the docker-compose.yml file:

```
...
  gogs:
    image: gogs/gogs:0.9.46
    container_name: gogs
    dns_search: .
    ports:
      - "10080:3000"
    volumes:
      - gogs-data:/data
    links:
      - db
...
```

see
https://docs.docker.com/compose/compose-file/#/dns-search
https://docs.docker.com/v1.11/engine/userguide/networking/default_network/configure-dns/

> Use --dns-search=. if you don't wish to set the search domain.
