### ISSUE TITLE
Repository clone panel overlaps file upload button

### ISSUE THREAD

**Issue by rugk** [gogits/gogs#3576]
- Gogs version (or commit ref): v0.9.97
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
  - [x] Not relevant
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No (because it is configured differently)
  - [ ] Not relevant
- Log gist: not relevant

## Description

The clone URL overlaps the 

![gogstoomuch](https://cloud.githubusercontent.com/assets/11966684/18170475/c6461b12-705e-11e6-88f9-0ead9144ea0c.png)

This seems to be relevant:
* The language is set to German, the translated string may be longer than thought
* SSH is disabled, so that there is no "switch button" on the left of the clone URL
* I am using the server in offline modus

BTW what's also interesting is that on my instance the button text is **bold** as set in the CSS file "semantic-2.2.1.min.css":
```css
.ui.button {
  [...]
  font-weight: 700;
  [...]
}
```

![gogstoomuch](https://cloud.githubusercontent.com/assets/11966684/18170475/c6461b12-705e-11e6-88f9-0ead9144ea0c.png)

Whereas on try.gogs.io is is overwritten by ["gogs.css"](https://try.gogs.io/css/gogs.css?v=acefd5d8b8b941fc7561c058ac2f5ad6):
```css
.repository.file.list #file-buttons .ui.button {
  [...]
  font-weight: normal;
  [...]
}
```

![gogsokay](https://cloud.githubusercontent.com/assets/11966684/18170771/d76ce2a8-705f-11e6-81fc-ff2c46fa3455.png)
