### ISSUE TITLE
Feature request: Read database password/secret key from file

### ISSUE THREAD

**Issue by rvl** [gogits/gogs#4445]
- Gogs version (or commit ref): 0.10.18
- Git version: 2.12.2
- Operating system: NixOS
- Database (use `[x]`):
  - [X] PostgreSQL
  - [X] MySQL
  - [X] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist (usually found in `log/gogs.log`): N/A

## Description

In some deployment environments (e.g. NixOS), it's better that passwords aren't stored in plaintext in the config file. It would be convenient if Gogs were able to read the password from a file.

Is it possible to add an option for this? e.g.

```
[database]
PASSWD_FILE = /run/keys/gogs-db-password
[security]
SECRET_KEY_FILE = /run/keys/gogs-secret-key
[mailer]
PASSWD_FILE = /run/keys/gogs-smtp-password
```

Related to #3134.

**Comment by TeoTN** [comment]
I'd like to add that it's considered very good practice while using docker, since it has the encrypted mechanism of secrets - it'd enable following config:
`docker-compose.yml`:
```
version: '3.5'
services:
  gogs:
    image: gogs/gogs
    ...
    secrets:
      - source: db_credentials
        target: /etc/gogs/.dbpasswd

secrets:
  db_credentials:
    file: /secret/location/mydb-passwd.txt
```
`app.ini`
```
[database]
CREDENTIALS_FILE = /etc/gogs/.dbpasswd
```
