### ISSUE TITLE
restart the docker container ,web page not restart

### ISSUE THREAD

**Issue by treemore** [gogits/gogs#4668]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).
2. Please post questions or config/deploy problems on our forum: https://discuss.gogs.io, here are bugs and feature requests only.
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports; incomplete details considered invalid report.

**You MUST delete above content including this line before posting; too lazy to take this action considered invalid report.**

- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
the docker-compose.yml is here
```yml
version: "2"
services:
        gogs:
          image: gogs/gogs
          volumes:
              - ./data:/data
          ports:
              - "10022:22"
              - "10080:3000"
```

the first time . i do docker-compose up gogs . and fellow the document . ervery was fine .
but . some days  later.  i restart the gogs service . git is ok, my friends can git push normal . 
but i can't enter  the manger web page http://localhost:10080.   so i try to enter the container and curl.
docker-compose exec gogs sh
then curl http://localhost:3000.  not work. so i belief the web not restart .

...
