### ISSUE TITLE
Docker / MySQL "syntax to use near 'utf8' at line 1" during install

### ISSUE THREAD

**Issue by AlbinoGeek** [gogits/gogs#4887]
- Gogs version (or commit ref):
        0.11.33.1119
- Git version:
        1.8.3.1
- Operating system:
        CentOS 7 (Docker-CE)
- Database:
  - [X] MySQL
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

I cannot proceed with the installation of Gogs using Docker-CE on CentOS 7 and your supplied image.  I am launching it using Docker-Compose as follows, I have tested the MySQL connection and found it working.  Originally I tried MariaDB but this failed in the same way.

**I have verified that MySQL works and can be contacted via another docker container.**

### `docker-compose.yaml`

```yaml
version: "3.2"
services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
  web:
    image: gogs/gogs:latest
    links:
      - mysql
    ports:
      - 22:10022
      - 3000:10080
    restart: always
    volumes:
      - ./gogs-data:/data
```

**MySQL root password, database, and user created using environment variables.**

## Error

Shown in the installer located at http://localhost:10080/install via the host.

Database setting is not correct: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'utf8' at line 1

![MySQL Syntax Error near utf8 at line 1](https://i.imgur.com/Z5JIqrL.png)
