### ISSUE TITLE
ssh failed

### ISSUE THREAD

**Issue by Pimaweichai** [gogits/gogs#4900]
Gogs version (or commit ref): docker image gogs/gogs:latest
Git version: 2.11.0
Operating system: ubuntu_16_0402_64
Database (use [x]):
  _MySQL_
Can you reproduce the bug at https://try.gogs.io:
  _No_
Description:
**I create gogs by docker and the docker-compose as below:**
```
    mysql:
        image: mysql:latest
        ports:
            - 3306:3306
        expose:
            - '3306'
        volumes:
            - ~/services/mysql/data:/var/lib/mysql
    gogs:
        image: gogs/gogs:latest
        ports:
            - '10022:22'
        expose:
            - '3000'
        volumes:
            - ~/services/gogs/data:/data
            - ~/services/gogs/docker:/app/gogs/docker
        links:
            - mysql
```

**And init the gogs by the install page, the config file of gogs is as below:**
```
      [server]
      DOMAIN           = git.mysite.cn
      HTTP_PORT        = 3000
      ROOT_URL         = https://git.mysite.cn/
      DISABLE_SSH      = false
      SSH_PORT         = 10022
      START_SSH_SERVER = true
      OFFLINE_MODE     = false
```
**Then I add my public key by web ui .And create a new repository name test.**
**When I git clone it by ssh links. It show me as below:**

_$ git clone ssh://git@git.mysite.cn:10022/roy/test.git
Cloning into 'test'...
The authenticity of host '[git.mysite.cn]:10022 ([57.76.29.114]:10022)' can't be established.
ECDSA key fingerprint is SHA256:xoLkuhHKKZntZ9CQtPcLJiYLS5aIuK4GkSQs0ENFdW8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[git.mysite.cn]:10022,[57.76.29.114]:10022' (ECDSA) to the list of known hosts.
git@git.mysite.cn's password:
Permission denied, please try again.
git@git.mysite.cn's password:
Permission denied, please try again.
git@git.mysite.cn's password:
Permission denied (publickey,password,keyboard-interactive).
fatal: Could not read from remote repository._

**Thanks a lot**
