### ISSUE TITLE
Avatar resize with aspect ratio

### ISSUE THREAD

**Issue by EtienneBruines** [gogits/gogs#893]
When uploading an avatar for a user, with dimensions 400x200, it is currently downscaled to 200x200.

Within `models/user.go`, in line 171, it calls the `resize.Resize` function. However, if you call `resize.Thumbnail` with exactly the same parameters, the image gets downscaled to 200x100 - <b>maintaining aspect ratio</b>. 

It should be noted that, if the image is much higher than it is wide, the UI would have to be updated as well. 

i.e.: within `public/ng/css/gogs.css` there are classes such as `img.avatar-20`, defining:
```css
img.avatar-20 {
  width: 20px;
  height: 20px;
  vertical-align: middle;
}
```
Taking out either the `width` or the `height`, would make it keep aspect ratio in the browser as well.
